version: '3.9'

services:
  composer:
    build: 
      context: ./
      dockerfile: ./dockerfiles/utility-tools.dockerfile
      target: composer
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    container_name: composer
  npm:
    build:
      context: ./
      dockerfile: ./dockerfiles/utility-tools.dockerfile
      target: node
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
    container_name: npm