version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID
        - GID
        - WEB_SERVER_UNSECURED_PORT
        - WEB_SERVER_SECURED_PORT
    volumes:
      - ./src:/var/www/api
      - ./app:/var/www/app
    restart: unless-stopped
    container_name: composer
