version: '3.9'

services:
  web_server:
    build:
      context: .
      dockerfile: ./dockerfiles/web_server.dockerfile
      args:
        - UID
        - GID
        - CONTAINER_USER
        - CONTAINER_GROUP
        - CONTAINER_PASSWORD
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/self-signed-cert:/var/www/self-signed-cert
      - ./src:/var/www/html
    restart: unless-stopped
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - app
      - sql_database
      # - nosql_database
      - cache
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
      args:
        - UID
        - GID
        - CONTAINER_USER
        - CONTAINER_GROUP
        - CONTAINER_PASSWORD
    volumes:
      - ./src:/var/www/html
    ports:
      - 22:22
    container_name: app
    restart: unless-stopped
    depends_on:
      - sql_database
      # - nosql_database
      - cache
  sql_database:
    build:
      context: .
      dockerfile: ./dockerfiles/sql_database.dockerfile
      args:
        - UID
        - GID
        - CONTAINER_USER
        - CONTAINER_GROUP
        - CONTAINER_PASSWORD
    restart: unless-stopped
    volumes:
      - sql_database_volume:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
      - 13306:22
    container_name: mysql
  nosql_database:
    build:
      context: .
      dockerfile: ./dockerfiles/nosql_database.dockerfile
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - nosql_database_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    container_name: mongodb
  cache:
    build:
      context: .
      dockerfile: ./dockerfiles/cache.dockerfile
      args:
        - CACHE_PASSWORD=$DATABASE_PASSWORD
    restart: unless-stopped
    volumes:
      - cache_volume:/data
    ports:
      - 6379:6379
    container_name: redis
volumes:
  cache_volume:
  sql_database_volume:
  nosql_database_volume:
