version: '3.9'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./dockerfiles/nginx.dockerfile
    volumes:
        - ./src:/var/www/html/backend
    ports:
      - '80:80'
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
      - mysql
      - mongodb
      - redis
  php:
    build:
      context: ./
      dockerfile: ./dockerfiles/php.dockerfile
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html/backend:delegated
    container_name: php
  mysql:
    build:
      context: ./
      dockerfile: ./dockerfiles/database.dockerfile
      target: mysql
    restart: unless-stopped
    volumes:
      - mysqld:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    ports:
      - '3306:3306'
    container_name: mysql
  mongodb:
    build:
      context: ./
      dockerfile: ./dockerfiles/database.dockerfile
      target: mongodb
    restart: unless-stopped
    volumes:
      - mongod:/data/db
    env_file:
      - ./env/mongodb.env
    ports:
      - '27017:27017'
    container_name: mongodb
  redis:
    build:
      context: ./
      dockerfile: ./dockerfiles/database.dockerfile
      target: redis
    restart: unless-stopped
    volumes:
      - redisd:/data
    ports:
      - '6379:6379'
    container_name: redis
  artisan:
    build:
      context: ./
      dockerfile: ./dockerfiles/php.dockerfile
    entrypoint: [ "php", "/var/www/html/backend/artisan" ]
    volumes:
      - ./src:/var/www/html/backend
    user: www-data
    container_name: artisan
  composer:
    build: 
      context: ./
      dockerfile: ./dockerfiles/utility-tools.dockerfile
      target: composer
    volumes:
      - ./src:/var/www/html/backend
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    container_name: composer
  npm:
    build:
      context: ./
      dockerfile: ./dockerfiles/utility-tools.dockerfile
      target: node
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html/backend
    container_name: npm

volumes:
  mysqld:
  mongod:
  redisd: