version: '3.9'

services:
  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/composer.dockerfile
      args:
        - UID
        - GID
        - WEB_SERVER_UNSECURED_PORT
        - WEB_SERVER_SECURED_PORT
    env_file:
      - .env.dev
    tty: true
    stdin_open: true
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
    container_name: composer
